export const GET_WRITER_LIST = 'home/GET_WRITER_LIST'
export const INIT_WRITER_LIST = 'home/INIT_WRITER_LIST'
export const GET_HOME_INFO = 'home/GET_HOME_INFO'
export const INIT_HOME_INFO = 'home/INIT_HOME_INFO'
export const GET_MORE_LIST = 'home/GET_MORE_LIST'
export const ADD_HOME_LIST = 'home/ADD_HOME_LIST'
export const TOGGLE_TOP_SHOW = 'home/TOGGLE_TOP_SHOW'